apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: compact_volume_set
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: cluster.ocs.openshift.io/openshift-storage
        operator: In
        values:
        - ""
  storageClassDevices:
    - storageClassName: local_volume_set-sc
      volumeMode: Block
      devicePaths:
        - /dev/nvme1n1