apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: compact-volume-set
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: cluster.ocs.openshift.io/openshift-storage
        operator: In
        values:
        - ""
  storageClassDevices:
    - storageClassName: local-volume-set-sc
      volumeMode: Block
      devicePaths:
        - /dev/disk/by-id/nvme-QEMU_NVMe_Ctrl_nvmedata2